function TDL_IUPS_GenerateGraphs
    % TDL_IUPS_GenerateGraphs Creates the graphs using data generated by TDL_IUPS_GenerateResults
    %
    % Before calling this script, run the script TDL_IUPS_GenerateResults.
    %
    % This script will display the generated results, which match the
    % results presented at IUPS 2009 by Doel et al:
    %
    %   Assessing the relative influence of vascular branching structure on pulmonary blood flow distribution via computational models
    %   T Doel, KS Burrowes, JP Whiteley, V Grau, DJ Gavaghan
    %   IUPS, Journal of Physiological Sciences 59, 224 (2009)
    %
    %
    %     Author: Tom Doel www.tomdoel.com
    %     Part of TreeSolve. http://github.com/tomdoel/TreeSolve
    %     Distributed under the GNU GPL v3 licence. Please see LICENSE file.
    %   

    TDL_AddPaths;
    
    results_set_to_use = '0';
    r1 = load(['Results/iups_pois_grav_prbif_prbcs_' results_set_to_use '/iups_pois_grav_prbif_prbcs_.mat']);
    r2 = load(['Results/iups_navs_grav_prbif_impbcs_' results_set_to_use '/iups_navs_grav_prbif_impbcs_.mat']);
    r3 = load(['Results/iups_navs_ng_prbif_impbcs_' results_set_to_use '/iups_navs_ng_prbif_impbcs_.mat']);
    r4 = load(['Results/iups_pois_grav_prbif_impbcs_' results_set_to_use '/iups_pois_grav_prbif_impbcs_.mat']);
    r5 = load(['Results/iups_pois_grav_mombif_impbcs_' results_set_to_use '/iups_pois_grav_mombif_impbcs_.mat']);

    TDL_CreateFolders('ResultsGraphs');
    
    % Comparison of Poisiuille Flow and Navier-Stokes (no gravity)
    TDL_PlotCompareFlows(r4, r3, 'Poiseuille flow', 'Navier-Stokes', fullfile('ResultsGraphs', 'iups_pois_vs_ns'));

    % Comparison of gravity and no gravity (navier-stokes)
    TDL_PlotCompareFlows(r2, r3, 'gravity', 'no gravity', fullfile('ResultsGraphs', 'iups_grav_vs_nograv'));

    % Comparison of pressure and impedance boundary conditions (Poiseuille)
    TDL_PlotCompareFlows(r1, r4, 'pressure boundaries', 'impedance/flow boundaries', fullfile('ResultsGraphs', 'iups_press_vs_imp_bcs'));

    % Comparison of pressure and momentum bifurcation equations
    TDL_PlotCompareFlows(r4, r5, 'pressure conservation', 'momentum conservation', fullfile('ResultsGraphs', 'iups_press_vs_mom_bif'));
    
    close all;
end 